version: '3.8'
# Configuration for the Docker Compose file version 3.8

services:
    # Define the services that make up your application, so they can be run together in an isolated environment.
    app:
        # Configuration for the 'app' service.
        build:
            # Build configuration for the service.
            context: . # The context is the set of files located in the current directory.
            dockerfile: Dockerfile # Specifies which Dockerfile to use for the build process.
        ports:
            - '5000:5000' # Binds the host port 3000 to the container port 3000.
            - '5001:5001' # Binds the host port 3001 to the container port 3001 for Next.js' hot-reloading.
        env_file:
            - .env.production # Specifies the environment file to load environment variables from.
        volumes:
            - .:/usr/src/app # Mounts the current directory into the container at /usr/src/app.
            - /usr/src/app/node_modules # Persists node_modules folder to prevent recreation on each build.
        restart: unless-stopped
        # The container will restart unless it is explicitly stopped.
        environment:
            - NODE_ENV=production # Sets the NODE_ENV environment variable to 'production'.
            - DEBUG=true # Enables debugging capabilities by setting the DEBUG environment variable to true.
            - NEXT_PUBLIC_NODE_ENV=production # Ensures Next.js uses the correct environment.
        command: yarn dev
        # Command to run the Next.js production server.
